### ISSUE TITLE
NW.js error: TypeError: Cannot read property 'subtle' of undefined (cryptographer)

### ISSUE THREAD

**Issue by jorisbontje** [ethereum/vapor#10]
```
$ ./dist/node-webkit/Vapor/osx64/Vapor.app/Contents/MacOS/nwjs
[9271:0307/113444:ERROR:nw_shell.cc(335)] TypeError: Cannot read property 'subtle' of undefined
    at Object.<anonymous> (file:///Users/mids/Projects/ethereum/vapor/dist/node-webkit/Vapor/osx64/Vapor.app/Contents/Resources/app.nw/app.js:26453:68)
    at Object.210.async (file:///Users/mids/Projects/ethereum/vapor/dist/node-webkit/Vapor/osx64/Vapor.app/Contents/Resources/app.nw/app.js:26662:4)
    at s (file:///Users/mids/Projects/ethereum/vapor/dist/node-webkit/Vapor/osx64/Vapor.app/Contents/Resources/app.nw/app.js:1:254)
    at file:///Users/mids/Projects/ethereum/vapor/dist/node-webkit/Vapor/osx64/Vapor.app/Contents/Resources/app.nw/app.js:1:305
    at Object.208../worker.js (file:///Users/mids/Projects/ethereum/vapor/dist/node-webkit/Vapor/osx64/Vapor.app/Contents/Resources/app.nw/app.js:26334:24)
    at s (file:///Users/mids/Projects/ethereum/vapor/dist/node-webkit/Vapor/osx64/Vapor.app/Contents/Resources/app.nw/app.js:1:254)
    at file:///Users/mids/Projects/ethereum/vapor/dist/node-webkit/Vapor/osx64/Vapor.app/Contents/Resources/app.nw/app.js:1:305
    at Object.<anonymous> (file:///Users/mids/Projects/ethereum/vapor/dist/node-webkit/Vapor/osx64/Vapor.app/Contents/Resources/app.nw/app.js:26394:21)
    at Object.209../index.js (file:///Users/mids/Projects/ethereum/vapor/dist/node-webkit/Vapor/osx64/Vapor.app/Contents/Resources/app.nw/app.js:26450:4)
    at s (file:///Users/mids/Projects/ethereum/vapor/dist/node-webkit/Vapor/osx64/Vapor.app/Contents/Resources/app.nw/app.js:1:254)
[9271:0307/113444:INFO:CONSOLE(26453)] "Uncaught TypeError: Cannot read property 'subtle' of undefined", source: file:///Users/mids/Projects/ethereum/vapor/dist/node-webkit/Vapor/osx64/Vapor.app/Contents/Resources/app.nw/app.js (26453)
```

**Comment by wanderer** [comment]
I'm assuming that NW.js doesn't have the crypto api. So will need to shim this.

**Comment by kumavis** [comment]
yeah need to deprecate node-webkit until cryptographe supports it

**Comment by kumavis** [comment]
Removed node-webkit support from launch goals, so im closing this issue
